### ISSUE TITLE
kinetics-video-classification: as-is script does not run

### ISSUE THREAD

**Issue by robert-s-lee** [gridai/grid-docs#25]
https://github.com/robert-s-lee/KineticsDemo/tree/fix-requirements.txt branch has WIP

Two issues:  https://docs.grid.ai/examples/vision/kinetics-video-classification

- fixed `No module named 'flash.data'`

fixed two typos in the code.
```
from flash.core.data.utils import download_data
from flash.core.utilities.imports import _KORNIA_AVAILABLE, _PYTORCHVIDEO_AVAILABLE
```

to fix
```
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from flash.data.utils import download_data
ModuleNotFoundError: No module named 'flash.data'
```

- need fix for `from pytorchvideo.transforms import ApplyTransformToKey, RandomShortSideScale, UniformTemporalSubsample`

```
% python train.py

/opt/miniconda3/envs/kd/lib/python3.7/site-packages/kornia/augmentation/augmentation.py:1833: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
Please, run `pip install torchvideo`
```

- To test

```
conda create --name=kd python=3.7
conda activate kd
pip install lightning-grid --upgrade
grid login 
git clone https://github.com/aribornstein/KineticsDemo.git
cd KineticsDemo
pip install -r requirements.txt 
```

**Comment by robert-s-lee** [comment]
```
pip install pytorchvideo
```

results in the next blocker

```
% python train.py

/opt/miniconda3/envs/kd/lib/python3.7/site-packages/kornia/augmentation/augmentation.py:1833: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from flash.video import VideoClassificationData, VideoClassifier
  File "/opt/miniconda3/envs/kd/lib/python3.7/site-packages/flash/video/__init__.py", line 1, in <module>
    from flash.video.classification.data import VideoClassificationData
  File "/opt/miniconda3/envs/kd/lib/python3.7/site-packages/flash/video/classification/data.py", line 46, in <module>
    from pytorchvideo.data.encoded_video_dataset import EncodedVideoDataset, labeled_encoded_video_dataset
ModuleNotFoundError: No module named 'pytorchvideo.data.encoded_video_dataset'
```

**Comment by pchitale1** [comment]
Thanks @robert-s-lee for reporting this issue, @aribornstein we need to look into this one

**Comment by pchitale1** [comment]
We have fixed the example code, @robert-s-lee , please try again and let me know if I can close the issue, thanks!

**Comment by robert-s-lee** [comment]
Fixed with https://github.com/aribornstein/KineticsDemo/pull/2
