### ISSUE TITLE
coco: fix the warning and errors

### ISSUE THREAD

**Issue by robert-s-lee** [gridai/grid-docs#27]
https://docs.grid.ai/examples/vision/coco run has the following warning and fails.  https://github.com/robert-s-lee/CocoDemo/tree/rslee-refresh has the WIP

```
/opt/conda/lib/python3.8/site-packages/pl_bolts/utils/warnings.py:30: UserWarning: You want to use `gym` which is not in
stalled yet, install it with `pip install gym`.
  stdout_func(
/opt/conda/lib/python3.8/site-packages/pl_bolts/utils/warnings.py:30: UserWarning: You want to use `cv2` which is not in
stalled yet, install it with `pip install opencv-python`.
  stdout_func(
```

fails with the following

```
  File "/opt/conda/lib/python3.8/site-packages/flash/core/trainer.py", line 90, in finetune
    return super().fit(model, train_dataloader, val_dataloaders, datamodule)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_trainin
g
    self.training_type_plugin.start_training(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 14
4, in start_training
    self._results = trainer.run_stage()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
    return self.run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 865, in run_train
    self.train_loop.on_train_epoch_start(epoch)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 169, in on_train_epoch_
start
    self.trainer.call_hook("on_train_epoch_start")
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1223, in call_hook
    trainer_hook(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py", line 90, in on_train_epoch_s
tart
    callback.on_train_epoch_start(self, self.lightning_module)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/finetuning.py", line 292, in on_train_epoch_s
tart
    self._store(pl_module, opt_idx, num_param_groups, current_param_groups)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/finetuning.py", line 278, in _store
    if opt_idx not in self._internal_state:
AttributeError: 'ObjectDetectionFineTuning' object has no attribute '_internal_state'
Training: 0it [00:00, ?it/s]
```

**Comment by robert-s-lee** [comment]
adding the following to `requirements.txt` has has the next issue:
```
opencv-python
gym
```

```
/opt/miniconda3/envs/kd/lib/python3.7/site-packages/pl_bolts/utils/warnings.py:32: UserWarning: You want to use `wandb` which is not installed yet, install it with `pip install wandb`.
```

**Comment by robert-s-lee** [comment]
adding `wand` yields the next blocker:

```
% python train.py
Traceback (most recent call last):
  File "train.py", line 2, in <module>
    import flash
  File "/opt/miniconda3/envs/kd/lib/python3.7/site-packages/flash/__init__.py", line 51, in <module>
    from flash import tabular, text, vision
  File "/opt/miniconda3/envs/kd/lib/python3.7/site-packages/flash/vision/__init__.py", line 1, in <module>
    from flash.vision.classification import ImageClassificationData, ImageClassifier
  File "/opt/miniconda3/envs/kd/lib/python3.7/site-packages/flash/vision/classification/__init__.py", line 2, in <module>
    from flash.vision.classification.model import ImageClassifier
  File "/opt/miniconda3/envs/kd/lib/python3.7/site-packages/flash/vision/classification/model.py", line 23, in <module>
    from flash.vision.backbones import backbone_and_num_features
  File "/opt/miniconda3/envs/kd/lib/python3.7/site-packages/flash/vision/backbones.py", line 23, in <module>
    from pl_bolts.models.self_supervised import SimCLR, SwAV
  File "/opt/miniconda3/envs/kd/lib/python3.7/site-packages/pl_bolts/__init__.py", line 19, in <module>
    from pl_bolts import (  # noqa: E402
  File "/opt/miniconda3/envs/kd/lib/python3.7/site-packages/pl_bolts/datamodules/__init__.py", line 5, in <module>
    from pl_bolts.datamodules.experience_source import DiscountedExperienceSource, ExperienceSource, ExperienceSourceDataset
  File "/opt/miniconda3/envs/kd/lib/python3.7/site-packages/pl_bolts/datamodules/experience_source.py", line 24, in <module>
    class ExperienceSourceDataset(IterableDataset):
  File "/opt/miniconda3/envs/kd/lib/python3.7/site-packages/torch/utils/data/_typing.py", line 273, in __new__
    return super().__new__(cls, name, bases, namespace, **kwargs)  # type: ignore[call-overload]
  File "/opt/miniconda3/envs/kd/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/opt/miniconda3/envs/kd/lib/python3.7/site-packages/torch/utils/data/_typing.py", line 371, in _dp_init_subclass
    ", but found {}".format(sub_cls.__name__, _type_repr(hints['return'])))
TypeError: Expected 'Iterator' as the return annotation for `__iter__` of ExperienceSourceDataset, but found typing.Iterable
```

**Comment by pchitale1** [comment]
@robert-s-lee When using CLI, we recommend to use conda. Please see the guidance here : https://docs.grid.ai/products/global-cli-configs/virtual-environments
