### ISSUE TITLE
CocoDemo: laptop and grid run instruction need refresh

### ISSUE THREAD

**Issue by robert-s-lee** [gridai/grid-docs#38]
https://docs.grid.ai/examples/vision/coco

local run fails

```
% python train.py --gpus=0 --max_epochs=1

/opt/miniconda3/envs/CocoDemo/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py:43: LightningDeprecationWarning: `pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package (https://github.com/PyTorchLightning/metrics) since v1.3 and will be removed in v1.5
  rank_zero_deprecation(
/opt/miniconda3/envs/CocoDemo/lib/python3.8/site-packages/pl_bolts/utils/warnings.py:30: UserWarning: You want to use `wandb` which is not installed yet, install it with `pip install wandb`.
  stdout_func(
/opt/miniconda3/envs/CocoDemo/lib/python3.8/site-packages/pl_bolts/utils/warnings.py:30: UserWarning: You want to use `gym` which is not installed yet, install it with `pip install gym`.
  stdout_func(
Traceback (most recent call last):
  File "train.py", line 2, in <module>
    import flash
  File "/opt/miniconda3/envs/CocoDemo/lib/python3.8/site-packages/flash/__init__.py", line 51, in <module>
    from flash import tabular, text, vision
  File "/opt/miniconda3/envs/CocoDemo/lib/python3.8/site-packages/flash/vision/__init__.py", line 1, in <module>
    from flash.vision.classification import ImageClassificationData, ImageClassifier
  File "/opt/miniconda3/envs/CocoDemo/lib/python3.8/site-packages/flash/vision/classification/__init__.py", line 2, in <module>
    from flash.vision.classification.model import ImageClassifier
  File "/opt/miniconda3/envs/CocoDemo/lib/python3.8/site-packages/flash/vision/classification/model.py", line 23, in <module>
    from flash.vision.backbones import backbone_and_num_features
  File "/opt/miniconda3/envs/CocoDemo/lib/python3.8/site-packages/flash/vision/backbones.py", line 23, in <module>
    from pl_bolts.models.self_supervised import SimCLR, SwAV
  File "/opt/miniconda3/envs/CocoDemo/lib/python3.8/site-packages/pl_bolts/__init__.py", line 19, in <module>
    from pl_bolts import (  # noqa: E402
  File "/opt/miniconda3/envs/CocoDemo/lib/python3.8/site-packages/pl_bolts/datamodules/__init__.py", line 5, in <module>
    from pl_bolts.datamodules.experience_source import DiscountedExperienceSource, ExperienceSource, ExperienceSourceDataset
  File "/opt/miniconda3/envs/CocoDemo/lib/python3.8/site-packages/pl_bolts/datamodules/experience_source.py", line 24, in <module>
    class ExperienceSourceDataset(IterableDataset):
  File "/opt/miniconda3/envs/CocoDemo/lib/python3.8/site-packages/torch/utils/data/_typing.py", line 273, in __new__
    return super().__new__(cls, name, bases, namespace, **kwargs)  # type: ignore[call-overload]
  File "/opt/miniconda3/envs/CocoDemo/lib/python3.8/abc.py", line 85, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/opt/miniconda3/envs/CocoDemo/lib/python3.8/site-packages/torch/utils/data/_typing.py", line 370, in _dp_init_subclass
    raise TypeError("Expected 'Iterator' as the return annotation for `__iter__` of {}"
TypeError: Expected 'Iterator' as the return annotation for `__iter__` of ExperienceSourceDataset, but found typing.Iterable
```

grid run fails the same way 

```
grid run train.py \
--gpus=0 \
--max_epochs=1

 % grid logs nocturnal-fox-57-exp0

[stdout] [2021-06-28T15:04:44.196149+00:00] /opt/conda/lib/python3.8/site-packages/pl_bolts/utils/warnings.py:30: UserWarning: You want to use `gym` which is not installed yet, install it with `pip install gym`.
[stdout] [2021-06-28T15:04:44.196182+00:00]   stdout_func(
[stdout] [2021-06-28T15:04:44.196187+00:00] /opt/conda/lib/python3.8/site-packages/pl_bolts/utils/warnings.py:30: UserWarning: You want to use `cv2` which is not installed yet, install it with `pip install opencv-python`.
[stdout] [2021-06-28T15:04:44.196191+00:00]   stdout_func(
[stdout] [2021-06-28T15:04:44.196194+00:00]
[stdout] [2021-06-28T15:04:44.284747+00:00] /gridai/project/data/coco128.zip:   0%|          | 0/21628 [00:00<?, ?KB/s]
[stdout] [2021-06-28T15:04:44.384739+00:00] /gridai/project/data/coco128.zip:   9%|▉         | 1969/21628 [00:00<00:00, 19687.72KB/s]
[stdout] [2021-06-28T15:04:44.484853+00:00] /gridai/project/data/coco128.zip:  29%|██▉       | 6242/21628 [00:00<00:00, 23486.98KB/s]
[stdout] [2021-06-28T15:04:44.593370+00:00] /gridai/project/data/coco128.zip:  44%|████▍     | 9550/21628 [00:00<00:00, 25718.71KB/s]
[stdout] [2021-06-28T15:04:44.684966+00:00] /gridai/project/data/coco128.zip:  65%|██████▍   | 13962/21628 [00:00<00:00, 29396.62KB/s]
[stdout] [2021-06-28T15:04:44.786345+00:00] /gridai/project/data/coco128.zip:  79%|███████▉  | 17157/21628 [00:00<00:00, 30117.44KB/s]
[stdout] [2021-06-28T15:04:44.798606+00:00] /gridai/project/data/coco128.zip:  97%|█████████▋| 21046/21628 [00:00<00:00, 32303.19KB/s]
[stdout] [2021-06-28T15:04:45.931534+00:00] /gridai/project/data/coco128.zip: 21629KB [00:00, 35413.58KB/s]
[stdout] [2021-06-28T15:04:45.931550+00:00] Downloading: "https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth" to /root/.cache/torch/hub/checkpoints/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth
[stdout] [2021-06-28T15:04:45.931555+00:00]
[stdout] [2021-06-28T15:04:46.016983+00:00]   0%|          | 0.00/160M [00:00<?, ?B/s]
[stdout] [2021-06-28T15:04:46.155178+00:00]   5%|▍         | 7.30M/160M [00:00<00:02, 76.1MB/s]
[stdout] [2021-06-28T15:04:46.244420+00:00]  11%|█         | 17.2M/160M [00:00<00:01, 82.0MB/s]
[stdout] [2021-06-28T15:04:46.314801+00:00]  15%|█▌        | 24.0M/160M [00:00<00:01, 78.5MB/s]
[stdout] [2021-06-28T15:04:46.414542+00:00]  21%|██        | 33.8M/160M [00:00<00:01, 84.5MB/s]
[stdout] [2021-06-28T15:04:46.516028+00:00]  27%|██▋       | 43.7M/160M [00:00<00:01, 89.4MB/s]
[stdout] [2021-06-28T15:04:46.619571+00:00]  34%|███▍      | 54.9M/160M [00:00<00:01, 95.9MB/s]
[stdout] [2021-06-28T15:04:46.719658+00:00]  41%|████      | 65.6M/160M [00:00<00:00, 99.5MB/s]
[stdout] [2021-06-28T15:04:46.819577+00:00]  47%|████▋     | 75.2M/160M [00:00<00:00, 99.7MB/s]
[stdout] [2021-06-28T15:04:46.919790+00:00]  54%|█████▍    | 86.4M/160M [00:00<00:00, 104MB/s]
[stdout] [2021-06-28T15:04:47.019646+00:00]  61%|██████    | 97.5M/160M [00:01<00:00, 108MB/s]
[stdout] [2021-06-28T15:04:47.131654+00:00]  68%|██████▊   | 108M/160M [00:01<00:00, 110MB/s]
[stdout] [2021-06-28T15:04:47.230091+00:00]  74%|███████▍  | 119M/160M [00:01<00:00, 108MB/s]
[stdout] [2021-06-28T15:04:47.323644+00:00]  81%|████████  | 130M/160M [00:01<00:00, 109MB/s]
[stdout] [2021-06-28T15:04:47.442097+00:00]  88%|████████▊ | 140M/160M [00:01<00:00, 110MB/s]
[stdout] [2021-06-28T15:04:47.602608+00:00]  94%|█████████▍| 151M/160M [00:01<00:00, 105MB/s]
[stdout] [2021-06-28T15:04:47.810078+00:00] 100%|██████████| 160M/160M [00:01<00:00, 99.0MB/s]
[stdout] [2021-06-28T15:04:47.810114+00:00] GPU available: False, used: False
[stdout] [2021-06-28T15:04:47.810240+00:00] TPU available: False, using: 0 TPU cores
[stdout] [2021-06-28T15:04:47.858016+00:00] /opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py:69: UserWarning: you defined a validation_step but have no val_dataloader. Skipping val loop
[stdout] [2021-06-28T15:04:47.858048+00:00]   warnings.warn(*args, **kwargs)
[stdout] [2021-06-28T15:04:47.858052+00:00]
[stdout] [2021-06-28T15:04:47.858056+00:00]   | Name    | Type       | Params
[stdout] [2021-06-28T15:04:47.858060+00:00] ---------------------------------------
[stdout] [2021-06-28T15:04:47.858064+00:00] 0 | model   | FasterRCNN | 41.8 M
[stdout] [2021-06-28T15:04:47.858068+00:00] 1 | metrics | ModuleDict | 0
[stdout] [2021-06-28T15:04:47.858072+00:00] ---------------------------------------
[stdout] [2021-06-28T15:04:47.858075+00:00] 15.0 M    Trainable params
[stdout] [2021-06-28T15:04:47.858079+00:00] 26.8 M    Non-trainable params
[stdout] [2021-06-28T15:04:47.858083+00:00] 41.8 M    Total params
[stdout] [2021-06-28T15:04:47.858086+00:00] 167.021   Total estimated model params size (MB)
[stdout] [2021-06-28T15:04:47.866515+00:00] loading annotations into memory...
[stdout] [2021-06-28T15:04:47.866577+00:00] Done (t=0.01s)
[stdout] [2021-06-28T15:04:47.866584+00:00] creating index...
[stdout] [2021-06-28T15:04:47.866588+00:00] index created!
[stdout] [2021-06-28T15:04:47.866592+00:00]
[stdout] [2021-06-28T15:04:47.866700+00:00] Validation sanity check: 0it [00:00, ?it/s]
[stdout] [2021-06-28T15:04:47.868226+00:00]
[stdout] [2021-06-28T15:04:47.868340+00:00]
[stdout] [2021-06-28T15:04:47.871139+00:00] Traceback (most recent call last):
[stdout] [2021-06-28T15:04:47.871153+00:00]   File "train.py", line 43, in <module>
[stdout] [2021-06-28T15:04:47.871158+00:00]     trainer.finetune(model, datamodule)
[stdout] [2021-06-28T15:04:47.871161+00:00]   File "/opt/conda/lib/python3.8/site-packages/flash/core/trainer.py", line 90, in finetune
[stdout] [2021-06-28T15:04:47.871166+00:00]     return super().fit(model, train_dataloader, val_dataloaders, datamodule)
[stdout] [2021-06-28T15:04:47.871170+00:00]   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
[stdout] [2021-06-28T15:04:47.871174+00:00]     self._run(model)
[stdout] [2021-06-28T15:04:47.871178+00:00]   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
[stdout] [2021-06-28T15:04:47.871182+00:00]     self.dispatch()
[stdout] [2021-06-28T15:04:47.871240+00:00]   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
[stdout] [2021-06-28T15:04:47.871247+00:00]     self.accelerator.start_training(self)
[stdout] [2021-06-28T15:04:47.871250+00:00]   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
[stdout] [2021-06-28T15:04:47.871254+00:00]     self.training_type_plugin.start_training(trainer)
[stdout] [2021-06-28T15:04:47.871258+00:00]   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
[stdout] [2021-06-28T15:04:47.871262+00:00]     self._results = trainer.run_stage()
[stdout] [2021-06-28T15:04:47.871266+00:00]   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
[stdout] [2021-06-28T15:04:47.871270+00:00]     return self.run_train()
[stdout] [2021-06-28T15:04:47.871273+00:00]   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 865, in run_train
[stdout] [2021-06-28T15:04:47.871277+00:00]     self.train_loop.on_train_epoch_start(epoch)
[stdout] [2021-06-28T15:04:47.871281+00:00]   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 169, in on_train_epoch_start
[stdout] [2021-06-28T15:04:47.871285+00:00]     self.trainer.call_hook("on_train_epoch_start")
[stdout] [2021-06-28T15:04:47.871288+00:00]   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1223, in call_hook
[stdout] [2021-06-28T15:04:47.871292+00:00]     trainer_hook(*args, **kwargs)
[stdout] [2021-06-28T15:04:47.871296+00:00]   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py", line 90, in on_train_epoch_start
[stdout] [2021-06-28T15:04:47.871300+00:00]     callback.on_train_epoch_start(self, self.lightning_module)
[stdout] [2021-06-28T15:04:47.871303+00:00]   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/finetuning.py", line 292, in on_train_epoch_start
[stdout] [2021-06-28T15:04:47.871307+00:00]     self._store(pl_module, opt_idx, num_param_groups, current_param_groups)
[stdout] [2021-06-28T15:04:47.871312+00:00]   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/finetuning.py", line 278, in _store
[stdout] [2021-06-28T15:04:47.871316+00:00]     if opt_idx not in self._internal_state:
[stdout] [2021-06-28T15:04:47.871320+00:00] AttributeError: 'ObjectDetectionFineTuning' object has no attribute '_internal_state'
```

**Comment by robert-s-lee** [comment]
https://github.com/gridai/grid-docs/issues/27 following up with my complete repro

```
git clone https://github.com/aribornstein/CocoDemo.git
cd CocoDemo
gridenv 
python train.py --gpus=0 --max_epochs=1
grid run train.py --gpus=0 --max_epochs=1
```

```
gridenv() {
  local name=${1:-$(basename -- $(pwd))}
  local pyver=${2:-3.8}
  local envexist=$(conda-env list | grep "^${name}[ \t]*")
  [ -z "${envexist}" ] && conda create --yes --name ${name} python=${pyver}
  conda activate ${name}
  [ -f requirements.txt ] && pip install -r requirements.txt
  pip install lightning-grid --upgrade
  [ ! -z "${GRID_API}" ] && grid login $GRID_API
}
```

**Comment by pchitale1** [comment]
So, you are trying the example with gpus=0 argument, and I think it won't work unless --gpus=1
